### ISSUE TITLE
Facing issues into compilation with ESP32 IDF 4.2 or 4.3 Release Version

### ISSUE THREAD

**Issue by Ritesh236** [jamieparkinson/ESP32-MAX31865#7] opened 2021-03-28 11:23 UTC
Hello,

We have tried to port repository as component with example into ESP32 IDF 4.2 or 4.3 Release but facing below issue. 

Has anyone faced this type of issue? if yes then how it can be resolved to move further.

![Screenshot (121)](https://user-images.githubusercontent.com/33974001/112750406-10adae80-8fe6-11eb-9fe5-0a7193b0241d.png)

Let me know if need anything else regarding steps for the same.

Regards,
Ritesh Prajapati

**Comment by jamieparkinson** [comment] 2021-03-28 16:53
I can't reproduce this when building the project in `/examples/simple` with idf v4.2 - it's hard to help from just a screenshot of an error message and no steps to reproduce. 

What version of C++ is your project using? Having googled the error message I think you're encountering this bug https://github.com/espressif/esp-idf/issues/5897 - please refer to the discussion there for workarounds. If you find that the solution requires a change to this library's config then please PR that change; otherwise I will close this issue.

**Comment by Ritesh236** [comment] 2021-03-28 17:19
> I can't reproduce this when building the project in `/examples/simple` with idf v4.2 - it's hard to help from just a screenshot of an error message and no steps to reproduce.
> 
> What version of C++ is your project using? Having googled the error message I think you're encountering this bug [espressif/esp-idf#5897](https://github.com/espressif/esp-idf/issues/5897) - please refer to the discussion there for workarounds. If you find that the solution requires a change to this library's config then please PR that change; otherwise I will close this issue.

Thanks @jamieparkinson for your quick and prompt response. 

Let me explain what we have did. 

Actually we are validating RTD sensor over ESP32 but we have already RTD to SPI module and PT100 RTD sensor itself. 

So we thought to check and validate that MAX31865 module in parallel. So we have already cloned ESP32 IDF Release 4.2 and 4.3 as per our requirements. 

Then we have added example with components and application file but while creating image it is causing that type of assertion which has been attached into first post. 

So would you please let us know with steps as you have already validated with 4.2 and 4.2 ESP32 IDF Release Version. Also let us know with which RTD sensor you have tested? And over VSPI or HSPI interface? 

Let me know if need anything else from my end. 

Regards, 
Ritesh Prajapati

**Comment by jamieparkinson** [comment] 2021-03-28 17:26
Ritesh; please refer to the linked issue in my initial response. Your problem is a compilation issue and so is not related to the sensor, the SPI interface, or the circuit config. Given that you can't provide steps to reproduce, and that I can't reproduce it by building the example in the repo using `idf.py build`, I am going to have to close this issue - I will re-open it if you can provide a minimal reproducible example.

**Closed as completed by jamieparkinson** 2021-03-28 17:26 UTC

**Comment by Ritesh236** [comment] 2021-03-28 17:32
> Ritesh; please refer to the linked issue in my initial response. Your problem is a compilation issue and so is not related to the sensor, the SPI interface, or the circuit config. Given that you can't provide steps to reproduce, and that I can't reproduce it by building the example in the repo using `idf.py build`, I am going to have to close this issue - I will re-open it if you can provide a minimal reproducible example.

@jamieparkinson , 

Sure. Let me check that link into details and apply changes which are mentioned into that link. 

BTW if you can provide commit I'd on which you have verified then I can verify directly on that commit as well. 

Also I will provide all steps which are followed by me with all details as soon as possible. 

I completely agreed on your point like that there is no any issue into SPI or Sensor code perspective as it is totally dependent on  C++ compilation environment. Also frankly I am saying that we have created project using ESP32 IDF over C Language till now and never compiled any C++ based component or example. 

Regards, 
Ritesh Prajapati

**Comment by Ritesh236** [comment] 2021-03-28 17:51
@jamieparkinson , 

Might be solution is like below into CMakeLists.txt

component_compile_options(-std=gnu++11) and component_compile_options(-std=gnu++17)

So we will check tomorrow or Tuesday with above solution and let you know if working or not. 

Thanks for your support and kind help for the same. 

Regards, 
Ritesh Prajapati
